"""
agent_media_sandbox/agent.py

Minimal agent that downloads a URL into a tmpfs sink.

There is no VAREK import here, and that is the point. The agent runs as an
ordinary Python process. Containment comes from launching it under Warden
using the policy generated by setup.sh:

    ./setup.sh
    sudo ./varek/v1_4/warden \\
        /tmp/agent-example/policy.txt \\
        -- python3 /tmp/agent-example/agent.py \\
           https://picsum.photos/seed/varek/800/600.jpg

Warden intercepts openat / connect / execve in this process and decides each
against policy.txt. Anything not explicitly allowed is denied; the agent
sees EACCES and either handles it or crashes — both are safer than the
unsandboxed outcome.

Framework note: drop this body into a tool function in Hermes Agent,
LangChain, LlamaIndex, or any agent framework. The wrapping happens at
process launch, so the framework lives outside the sandbox boundary.
"""

import hashlib
import socket
import sys
import urllib.parse
import urllib.request
from pathlib import Path

SINK = Path("/tmp/agent-example")
ALLOWED_MIME_PREFIXES = ("image/", "audio/", "video/")
MAX_BYTES = 25 * 1024 * 1024  # 25 MiB cap; tune to your policy


def download_media(url: str) -> Path:
    """Fetch URL into SINK, return the written path.

    Network egress and write paths are enforced by Warden against the
    policy file, below this layer. The MIME and size checks below are
    application-level guards layered on top of that floor.
    """
    SINK.mkdir(parents=True, exist_ok=True)

    parsed = urllib.parse.urlparse(url)
    if parsed.scheme != "https":
        raise ValueError(f"https only; got {parsed.scheme!r}")

    # If your policy allowlists the resolver (e.g. 127.0.0.53:53), this
    # getaddrinfo call succeeds. If your policy pins origin IPs instead,
    # resolve once here and rewrite the URL to the IP.
    socket.gethostbyname(parsed.hostname)

    req = urllib.request.Request(url, method="GET")
    with urllib.request.urlopen(req, timeout=10) as resp:
        ctype = resp.headers.get_content_type()
        if not ctype.startswith(ALLOWED_MIME_PREFIXES):
            raise ValueError(f"unexpected content-type: {ctype}")
        data = resp.read(MAX_BYTES + 1)
        if len(data) > MAX_BYTES:
            raise ValueError(f"response exceeded {MAX_BYTES} bytes")

    name = Path(parsed.path).name or "download.bin"
    out_path = SINK / name
    with open(out_path, "wb") as f:
        f.write(data)
    return out_path


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(f"usage: {argv[0]} <url>", file=sys.stderr)
        return 2

    url = argv[1]
    try:
        path = download_media(url)
    except PermissionError as e:
        # Warden denied a syscall. The pathology record on stderr names
        # the action and target.
        print(f"sandbox denied: {e}", file=sys.stderr)
        return 13
    except Exception as e:
        print(f"download failed: {type(e).__name__}: {e}", file=sys.stderr)
        return 1

    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    print(f"ok path={path} sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
