#!/usr/bin/env bash
# setup.sh — self-configuring setup for the agent-media-sandbox example.
#
# Generates /tmp/agent-example/policy.txt with rules derived from your
# actual environment: Python's sys.path, the agent host's resolved IPv4
# addresses (all of them), the system DNS resolver from /etc/resolv.conf,
# and the standard glibc/OpenSSL/locale config paths.
#
# Goal: first run of ./setup.sh followed by the printed warden invocation
# completes the download with no manual policy edits required.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SINK="/tmp/agent-example"
ORIGIN_HOST="${ORIGIN_HOST:-httpbin.org}"
DEMO_URL="${DEMO_URL:-https://$ORIGIN_HOST/image/jpeg}"
ORIGIN_PORT="${ORIGIN_PORT:-443}"
WARDEN_BIN="${WARDEN_BIN:-./varek/v1_4/warden}"

mkdir -p "$SINK"
cp "$HERE/agent.py" "$SINK/agent.py"

# Detect the Python interpreter once; reuse for both the allow-exec rule
# and sys.path resolution so both agree.
PYTHON_BIN="$(command -v python3 || true)"
if [ -z "$PYTHON_BIN" ]; then
    echo "ERROR: python3 not found in PATH" >&2
    exit 1
fi

# Resolve ALL IPv4 addresses for the origin host. Warden sees post-DNS IPs
# at the connect() syscall; getaddrinfo returns multiple A records for
# CDN-fronted hosts and Python tries each in turn, so every one must be
# allowlisted. IPv4-only because warden formats IPv6 connect targets as
# [addr]:port and the policy line `allow host <addr>:<port>` cannot
# disambiguate IPv6 colons from the port colon.
ORIGIN_IPS="$(getent ahostsv4 "$ORIGIN_HOST" | awk '{print $1}' | sort -u)"
if [ -z "$ORIGIN_IPS" ]; then
    echo "ERROR: could not resolve $ORIGIN_HOST to any IPv4 address" >&2
    exit 1
fi

# Read system DNS resolvers from /etc/resolv.conf instead of hardcoding
# a specific local resolver address. systemd-resolved uses 127.0.0.53;
# dnsmasq uses 127.0.0.1; some systems point directly at an upstream.
RESOLVER_LINES="$(awk '/^nameserver / && $2 ~ /^[0-9.]+$/ {print "allow host " $2 ":53"}' /etc/resolv.conf 2>/dev/null || true)"

# Resolve Python's actual sys.path entries for the active interpreter.
PY_PATHS="$("$PYTHON_BIN" -c 'import sys
for p in sys.path:
    if p:
        print(p)')"

{
    cat <<EOF
# Auto-generated by setup.sh
#   origin:   $ORIGIN_HOST -> $(echo "$ORIGIN_IPS" | tr '\n' ' ')
#   port:     $ORIGIN_PORT
#   python:   $PYTHON_BIN
#   resolver: from /etc/resolv.conf
# Re-run setup.sh whenever your Python install, origin, or resolver
# config changes.

# --- Process: the Python interpreter itself ---
allow exec $PYTHON_BIN

# --- Filesystem: media sink and the agent script ---
# Emit each directory twice: bare form matches openat() on the directory
# itself (Python reads the listing), trailing-slash form matches files
# within the directory under warden's prefix-match.
allow path $SINK
allow path $SINK/

# --- Filesystem: TLS trust store and OpenSSL config ---
# On Ubuntu /usr/lib/ssl/{certs,cert.pem,openssl.cnf} are symlinks into
# /etc/ssl. OpenSSL probes the /usr/lib/ssl side first, so both prefixes
# need allowlisting.
allow path /usr/lib/ssl
allow path /usr/lib/ssl/
allow path /etc/ssl
allow path /etc/ssl/
allow path /usr/share/ca-certificates
allow path /usr/share/ca-certificates/

# --- Filesystem: entropy source for TLS ---
allow path /dev/urandom

# --- Filesystem: shared libraries and loader cache ---
allow path /lib/x86_64-linux-gnu
allow path /lib/x86_64-linux-gnu/
allow path /usr/lib/x86_64-linux-gnu
allow path /usr/lib/x86_64-linux-gnu/
allow path /etc/ld.so.cache

# --- Filesystem: glibc resolver and locale config (getaddrinfo path) ---
allow path /etc/resolv.conf
allow path /etc/nsswitch.conf
allow path /etc/hosts
allow path /etc/host.conf
allow path /etc/gai.conf
allow path /etc/localtime

# --- Filesystem: Python's resolved sys.path ---
EOF
    echo "$PY_PATHS" | while IFS= read -r p; do
        echo "allow path $p"
        echo "allow path $p/"
    done

    cat <<EOF

# --- Network: pinned origin (all IPv4 addresses returned by resolver) ---
EOF
    echo "$ORIGIN_IPS" | while read -r ip; do
        echo "allow host $ip:$ORIGIN_PORT"
    done

    cat <<EOF

# --- Network: system DNS resolver(s) from /etc/resolv.conf ---
EOF
    if [ -n "$RESOLVER_LINES" ]; then
        echo "$RESOLVER_LINES"
    else
        echo "# (no IPv4 nameserver entries found in /etc/resolv.conf)"
    fi
} > "$SINK/policy.txt"

# Report
echo "wrote $SINK/agent.py"
echo "wrote $SINK/policy.txt"
echo "  python:   $PYTHON_BIN"
echo "  origin:   $ORIGIN_HOST -> $(echo "$ORIGIN_IPS" | tr '\n' ' ')"
echo "  port:     $ORIGIN_PORT"
RESOLVER_FIRST="$(echo "$RESOLVER_LINES" | head -1 | awk '{print $3}')"
echo "  resolver: ${RESOLVER_FIRST:-none found in /etc/resolv.conf}"
echo
echo "run:"
echo "  sudo $WARDEN_BIN \\"
echo "      $SINK/policy.txt \\"
echo "      -- $PYTHON_BIN $SINK/agent.py $DEMO_URL"
echo
echo "first-run note: if Warden denies a path the agent needs, the"
echo "pathology record on stderr names the target. Add an 'allow path'"
echo "rule and re-run. Distros other than Ubuntu 24.04 may surface a"
echo "few additional paths the static template does not cover yet."
