#!/usr/bin/env bash
# setup.sh — self-configuring setup for the agent-media-sandbox example.
#
# Eliminates the two environment-specific unknowns in policy.txt:
#
#   1. Python's stdlib + site-packages paths — resolved from the actual
#      sys.path of your python3, so the policy matches your install
#      (apt, pyenv, uv, conda, whatever) instead of a guess.
#
#   2. The origin host's resolved IP — Warden matches at the syscall layer
#      against the IP, not the hostname, so we resolve once here via getent
#      and pin that IP in the policy.
#
# Outputs:
#   /tmp/agent-example/agent.py
#   /tmp/agent-example/policy.txt
#
# Then prints the warden invocation to run.
#
# Override the origin or warden binary with env vars:
#   ORIGIN_HOST=images.unsplash.com ./setup.sh
#   WARDEN_BIN=/abs/path/to/warden ./setup.sh

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SINK="/tmp/agent-example"
ORIGIN_HOST="${ORIGIN_HOST:-picsum.photos}"
DEMO_URL="${DEMO_URL:-https://$ORIGIN_HOST/seed/varek/800/600.jpg}"
ORIGIN_PORT="${ORIGIN_PORT:-443}"
WARDEN_BIN="${WARDEN_BIN:-./varek/v1_4/warden}"

mkdir -p "$SINK"
cp "$HERE/agent.py" "$SINK/agent.py"

# Resolve origin host -> IP (warden sees the post-DNS address).
ORIGIN_IP="$(getent hosts "$ORIGIN_HOST" | awk '{print $1; exit}')"
if [ -z "$ORIGIN_IP" ]; then
    echo "ERROR: could not resolve $ORIGIN_HOST" >&2
    exit 1
fi

# Resolve Python's actual sys.path so the policy works in your env.
PY_PATHS="$(python3 -c 'import sys
for p in sys.path:
    if p:
        print(p)')"

{
    cat <<EOF
# Auto-generated by setup.sh
#   origin:  $ORIGIN_HOST -> $ORIGIN_IP:$ORIGIN_PORT
#   python:  $(command -v python3)
# Re-run setup.sh whenever your Python install or origin changes.

# --- Filesystem: media sink and the agent script
allow path $SINK/

# --- Filesystem: TLS trust store
allow path /etc/ssl/certs/
allow path /usr/share/ca-certificates/
allow path /etc/ssl/openssl.cnf

# --- Filesystem: entropy source for TLS
allow path /dev/urandom

# --- Filesystem: shared libraries (Linux loader)
allow path /lib/x86_64-linux-gnu/
allow path /usr/lib/x86_64-linux-gnu/
allow path /etc/ld.so.cache

# --- Filesystem: Python's resolved sys.path
EOF
    echo "$PY_PATHS" | while IFS= read -r p; do
        echo "allow path $p/"
    done

    cat <<EOF

# --- Network: pinned origin
allow host $ORIGIN_IP:$ORIGIN_PORT

# --- Network: system DNS resolver (delete this rule if you pre-resolve
# in the agent and connect to the pinned IP only)
allow host 127.0.0.53:53
EOF
} > "$SINK/policy.txt"

echo "wrote $SINK/agent.py"
echo "wrote $SINK/policy.txt"
echo "  origin: $ORIGIN_HOST -> $ORIGIN_IP:$ORIGIN_PORT"
echo
echo "run:"
echo "  sudo $WARDEN_BIN \\"
echo "      $SINK/policy.txt \\"
echo "      -- python3 $SINK/agent.py $DEMO_URL"
echo
echo "first-run note: if Warden denies a path the agent needs (e.g. a"
echo "config file under /etc/), the pathology record on stderr names the"
echo "target. Add an 'allow path' rule for it and re-run."
